minimumReleaseAgeExclude:
  - ansi-regex@6.4.0
  - eslint-plugin-n@18.4.0
  - micromark-core-commonmark@2.0.4
  - micromark-factory-space@2.1.0
  - micromark-util-edit-map@1.0.0
  - micromark-util-types@2.0.3
  - micromark@4.0.3

overrides:
  deepmerge-ts: 8.0.0
  sharp: 0.35.4
  svgo: 4.1.0

allowBuilds:
  esbuild: true
  simple-git-hooks: false
